name: dictionary_domain
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dictionary_dependencies_core:
    path: ../dictionary_dependencies_core
  freezed: ^2.4.2
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.1.2
